<a href="https://colab.research.google.com/github/neelamdhiren/Reinforcement-Learning/blob/main/RL_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
M = input("enter number of machines")
M = int(M)

machines = []

for i in range(M):
    name = input("enter machine name")
    machines.append(name)

print(machines)

enter number of machines3
enter machine nameA
enter machine nameB
enter machine nameC
['A', 'B', 'C']


In [3]:
import numpy as np

N_play = 5

N = np.zeros((M, N_play))
R = np.zeros((M, N_play))
Q = np.zeros((M, N_play))

Q_old = [0, 0, 0]

for machine in machines:
    print(f"Play with machine {machine}")

    r = input("enter reward")
    r = int(r)

    id = machines.index(machine)

    N[id, 0] = 1
    R[id, 0] = r
    Q[id, 0] = Q_old[0] + (R[id, 0] - Q_old[0]) / N[id, 0]

print(Q)
print(N)
print(R)

Play with machine A
enter reward3
Play with machine B
enter reward6
Play with machine C
enter reward4
[[3. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]]


In [4]:
import random

eps = 0.2
r = random.uniform(0, 1)

play = 1

while (play <= N_play - 1):

    Q[:, play] = Q[:, play - 1]
    r = random.uniform(0, 1)

    if (r < eps):
        print("Explore")

        id = random.randint(0, M - 1)  # Corrected to avoid IndexError

        print(f"Play with machine {machines[id]}")

        r = input("enter reward")
        r = int(r)

        N[id, play] = 1
        R[id, play] = r

        Q[id, play] = Q[id, play - 1] + (
            (R[id, play] - Q[id, play - 1]) /
            np.sum(N[id, :])
        )

    else:
        print("Exploit")

        id = np.argmax(Q[:, play - 1])

        print(f"Play with machine {machines[id]}")

        r = input("enter reward")
        r = int(r)

        N[id, play] = 1
        R[id, play] = r

        Q[id, play] = Q[id, play - 1] + (
            (R[id, play] - Q[id, play - 1]) /
            np.sum(N[id, :])
        )

    play = play + 1

Exploit
Play with machine B
enter reward6
Exploit
Play with machine B
enter reward7
Exploit
Play with machine B
enter reward5
Exploit
Play with machine B
enter reward4
